version: '2.1'

services:
  main:
    build:
      context: ./
      dockerfile: Dockerfile
    image: vdasari/lldp:latest
    container_name: lldp
    hostname: lldp
    volumes:
        - ${HOME}:${HOME}
    privileged: true
    cap_add:
      - ALL
      - NET_ADMIN
      - SYS_ADMIN
      - NET_BROADCAST
    networks:
      default_lldp_net:
        ipv4_address: 10.0.123.10
      network_lldp_1:
        ipv4_address: 10.0.100.1

  lldp1:
    build:
      context: ./
      dockerfile: Dockerfile
    image: vdasari/lldp:latest
    container_name: lldp1
    hostname: lldp1
    volumes:
        - ${HOME}:${HOME}
    entrypoint: |
      bash -c 'bash -s <<EOF
      lldpd 
      sleep infinity
      EOF'
    privileged: true
    cap_add:
      - ALL
      - NET_ADMIN
      - SYS_ADMIN
      - NET_BROADCAST
    networks:
      default_lldp_net:
        ipv4_address: 10.0.123.20
      network_lldp_1:
        ipv4_address: 10.0.100.2


networks:
  default_lldp_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.123.0/24
        gateway: 10.0.123.254
  network_lldp_1:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.100.0/24
        gateway: 10.0.100.254
