version: '2.1'

services:
  lldp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: vdasari/lldp:latest
    container_name: lldp
    hostname: lldp
    volumes:
        - ${HOME}:${HOME}
    privileged: true
    networks:
      default_lldp_net:
        ipv4_address: 10.0.123.10
      network_lldp_1:
        ipv4_address: 10.0.100.1
      network_lldp_2:
        ipv4_address: 10.0.101.1

  lldp1:
    build:
      context: ./
      dockerfile: Dockerfile
    image: vdasari/lldp:latest
    container_name: lldp1
    hostname: lldp1
    volumes:
        - ${HOME}:${HOME}
    entrypoint: |
      bash -c 'bash -s <<EOF
      lldpd 
      sleep infinity
      EOF'
    privileged: true
    networks:
      default_lldp_net:
        ipv4_address: 10.0.123.20
      network_lldp_1:
        ipv4_address: 10.0.100.2

  lldp2:
    build:
      context: ./
      dockerfile: Dockerfile
    image: vdasari/lldp:latest
    container_name: lldp2
    hostname: lldp2
    volumes:
        - ${HOME}:${HOME}
    entrypoint: |
      bash -c 'bash -s <<EOF
      lldpd
      sleep infinity
      EOF'
    privileged: true
    networks:
      default_lldp_net:
        ipv4_address: 10.0.123.30
      network_lldp_2:
        ipv4_address: 10.0.101.2


networks:
  default_lldp_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.123.0/24
        gateway: 10.0.123.254
  network_lldp_1:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.100.0/24
        gateway: 10.0.100.254
  network_lldp_2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.101.0/24
        gateway: 10.0.101.254
